import { WordPair } from '@duodeceit/shared';

export const WORD_PAIRS: WordPair[] = [
  // Fruits & Food (Easy & Medium)
  { id: 'f1', word1: 'Apple', word2: 'Orange', category: 'Food & Drinks', difficulty: 'easy' },
  { id: 'f2', word1: 'Pizza', word2: 'Burger', category: 'Food & Drinks', difficulty: 'easy' },
  { id: 'f3', word1: 'Coffee', word2: 'Tea', category: 'Food & Drinks', difficulty: 'easy' },
  { id: 'f4', word1: 'Pancake', word2: 'Waffle', category: 'Food & Drinks', difficulty: 'medium' },
  { id: 'f5', word1: 'Ice Cream', word2: 'Frozen Yogurt', category: 'Food & Drinks', difficulty: 'medium' },
  { id: 'f6', word1: 'Sushi', word2: 'Ramen', category: 'Food & Drinks', difficulty: 'easy' },
  { id: 'f7', word1: 'Chocolate', word2: 'Caramel', category: 'Food & Drinks', difficulty: 'medium' },
  { id: 'f8', word1: 'Bread', word2: 'Croissant', category: 'Food & Drinks', difficulty: 'medium' },
  { id: 'f9', word1: 'Butter', word2: 'Cheese', category: 'Food & Drinks', difficulty: 'medium' },
  { id: 'f10', word1: 'Cookie', word2: 'Brownie', category: 'Food & Drinks', difficulty: 'medium' },
  { id: 'f11', word1: 'Potato', word2: 'Sweet Potato', category: 'Food & Drinks', difficulty: 'hard' },
  { id: 'f12', word1: 'Lemonade', word2: 'Iced Tea', category: 'Food & Drinks', difficulty: 'easy' },
  { id: 'f13', word1: 'Strawberry', word2: 'Raspberry', category: 'Food & Drinks', difficulty: 'hard' },
  { id: 'f14', word1: 'Peach', word2: 'Apricot', category: 'Food & Drinks', difficulty: 'hard' },
  { id: 'f15', word1: 'Onion', word2: 'Garlic', category: 'Food & Drinks', difficulty: 'medium' },
  { id: 'f16', word1: 'Salt', word2: 'Sugar', category: 'Food & Drinks', difficulty: 'medium' },
  { id: 'f17', word1: 'Noodles', word2: 'Spaghetti', category: 'Food & Drinks', difficulty: 'hard' },
  { id: 'f18', word1: 'Milkshake', word2: 'Smoothie', category: 'Food & Drinks', difficulty: 'medium' },
  { id: 'f19', word1: 'Donut', word2: 'Bagel', category: 'Food & Drinks', difficulty: 'medium' },
  { id: 'f20', word1: 'Mayonnaise', word2: 'Mustard', category: 'Food & Drinks', difficulty: 'easy' },

  // Animals & Wildlife
  { id: 'a1', word1: 'Cat', word2: 'Dog', category: 'Animals', difficulty: 'easy' },
  { id: 'a2', word1: 'Lion', word2: 'Tiger', category: 'Animals', difficulty: 'easy' },
  { id: 'a3', word1: 'Dolphin', word2: 'Whale', category: 'Animals', difficulty: 'easy' },
  { id: 'a4', word1: 'Eagle', word2: 'Falcon', category: 'Animals', difficulty: 'medium' },
  { id: 'a5', word1: 'Frog', word2: 'Toad', category: 'Animals', difficulty: 'hard' },
  { id: 'a6', word1: 'Crocodile', word2: 'Alligator', category: 'Animals', difficulty: 'hard' },
  { id: 'a7', word1: 'Rabbit', word2: 'Hamster', category: 'Animals', difficulty: 'easy' },
  { id: 'a8', word1: 'Bee', word2: 'Wasp', category: 'Animals', difficulty: 'hard' },
  { id: 'a9', word1: 'Wolf', word2: 'Fox', category: 'Animals', difficulty: 'medium' },
  { id: 'a10', word1: 'Horse', word2: 'Donkey', category: 'Animals', difficulty: 'medium' },
  { id: 'a11', word1: 'Crow', word2: 'Raven', category: 'Animals', difficulty: 'hard' },
  { id: 'a12', word1: 'Turtle', word2: 'Tortoise', category: 'Animals', difficulty: 'hard' },
  { id: 'a13', word1: 'Moth', word2: 'Butterfly', category: 'Animals', difficulty: 'medium' },
  { id: 'a14', word1: 'Cheetah', word2: 'Leopard', category: 'Animals', difficulty: 'hard' },
  { id: 'a15', word1: 'Duck', word2: 'Goose', category: 'Animals', difficulty: 'medium' },
  { id: 'a16', word1: 'Mouse', word2: 'Rat', category: 'Animals', difficulty: 'medium' },
  { id: 'a17', word1: 'Seal', word2: 'Sea Lion', category: 'Animals', difficulty: 'hard' },
  { id: 'a18', word1: 'Gorilla', word2: 'Chimpanzee', category: 'Animals', difficulty: 'medium' },
  { id: 'a19', word1: 'Llama', word2: 'Alpaca', category: 'Animals', difficulty: 'hard' },
  { id: 'a20', word1: 'Owl', word2: 'Bat', category: 'Animals', difficulty: 'easy' },

  // Nature, Weather & Geography
  { id: 'n1', word1: 'Mountain', word2: 'Hill', category: 'Nature & Places', difficulty: 'easy' },
  { id: 'n2', word1: 'Ocean', word2: 'Sea', category: 'Nature & Places', difficulty: 'medium' },
  { id: 'n3', word1: 'River', word2: 'Lake', category: 'Nature & Places', difficulty: 'easy' },
  { id: 'n4', word1: 'Sun', word2: 'Moon', category: 'Nature & Places', difficulty: 'easy' },
  { id: 'n5', word1: 'Rain', word2: 'Snow', category: 'Nature & Places', difficulty: 'easy' },
  { id: 'n6', word1: 'Forest', word2: 'Jungle', category: 'Nature & Places', difficulty: 'medium' },
  { id: 'n7', word1: 'Beach', word2: 'Desert', category: 'Nature & Places', difficulty: 'easy' },
  { id: 'n8', word1: 'Cave', word2: 'Tunnel', category: 'Nature & Places', difficulty: 'medium' },
  { id: 'n9', word1: 'Island', word2: 'Peninsula', category: 'Nature & Places', difficulty: 'hard' },
  { id: 'n10', word1: 'Tornado', word2: 'Hurricane', category: 'Nature & Places', difficulty: 'hard' },
  { id: 'n11', word1: 'Fog', word2: 'Mist', category: 'Nature & Places', difficulty: 'hard' },
  { id: 'n12', word1: 'Breeze', word2: 'Gust', category: 'Nature & Places', difficulty: 'hard' },
  { id: 'n13', word1: 'Stream', word2: 'Creek', category: 'Nature & Places', difficulty: 'hard' },
  { id: 'n14', word1: 'Volcano', word2: 'Earthquake', category: 'Nature & Places', difficulty: 'easy' },
  { id: 'n15', word1: 'Pond', word2: 'Puddle', category: 'Nature & Places', difficulty: 'medium' },
  { id: 'n16', word1: 'Lightning', word2: 'Thunder', category: 'Nature & Places', difficulty: 'medium' },
  { id: 'n17', word1: 'Canyon', word2: 'Valley', category: 'Nature & Places', difficulty: 'hard' },
  { id: 'n18', word1: 'Glacier', word2: 'Iceberg', category: 'Nature & Places', difficulty: 'hard' },
  { id: 'n19', word1: 'Waterfall', word2: 'Fountain', category: 'Nature & Places', difficulty: 'medium' },
  { id: 'n20', word1: 'Swamp', word2: 'Marsh', category: 'Nature & Places', difficulty: 'hard' },

  // Everyday Objects & Tools
  { id: 'o1', word1: 'Pen', word2: 'Pencil', category: 'Everyday Objects', difficulty: 'easy' },
  { id: 'o2', word1: 'Fork', word2: 'Spoon', category: 'Everyday Objects', difficulty: 'easy' },
  { id: 'o3', word1: 'Cup', word2: 'Mug', category: 'Everyday Objects', difficulty: 'medium' },
  { id: 'o4', word1: 'Chair', word2: 'Stool', category: 'Everyday Objects', difficulty: 'medium' },
  { id: 'o5', word1: 'Blanket', word2: 'Pillow', category: 'Everyday Objects', difficulty: 'easy' },
  { id: 'o6', word1: 'Glasses', word2: 'Sunglasses', category: 'Everyday Objects', difficulty: 'medium' },
  { id: 'o7', word1: 'Clock', word2: 'Watch', category: 'Everyday Objects', difficulty: 'medium' },
  { id: 'o8', word1: 'Backpack', word2: 'Suitcase', category: 'Everyday Objects', difficulty: 'easy' },
  { id: 'o9', word1: 'Mirror', word2: 'Window', category: 'Everyday Objects', difficulty: 'medium' },
  { id: 'o10', word1: 'Candle', word2: 'Flashlight', category: 'Everyday Objects', difficulty: 'easy' },
  { id: 'o11', word1: 'Stool', word2: 'Bench', category: 'Everyday Objects', difficulty: 'hard' },
  { id: 'o12', word1: 'Knife', word2: 'Scissors', category: 'Everyday Objects', difficulty: 'easy' },
  { id: 'o13', word1: 'Sofa', word2: 'Bed', category: 'Everyday Objects', difficulty: 'easy' },
  { id: 'o14', word1: 'Boots', word2: 'Sneakers', category: 'Everyday Objects', difficulty: 'medium' },
  { id: 'o15', word1: 'Comb', word2: 'Hairbrush', category: 'Everyday Objects', difficulty: 'hard' },
  { id: 'o16', word1: 'Bucket', word2: 'Bowl', category: 'Everyday Objects', difficulty: 'medium' },
  { id: 'o17', word1: 'Shampoo', word2: 'Soap', category: 'Everyday Objects', difficulty: 'medium' },
  { id: 'o18', word1: 'Wallet', word2: 'Purse', category: 'Everyday Objects', difficulty: 'hard' },
  { id: 'o19', word1: 'Notebook', word2: 'Diary', category: 'Everyday Objects', difficulty: 'hard' },
  { id: 'o20', word1: 'Ruler', word2: 'Tape Measure', category: 'Everyday Objects', difficulty: 'medium' },

  // Technology & Vehicles
  { id: 't1', word1: 'Bus', word2: 'Train', category: 'Tech & Transport', difficulty: 'easy' },
  { id: 't2', word1: 'Car', word2: 'Motorcycle', category: 'Tech & Transport', difficulty: 'easy' },
  { id: 't3', word1: 'Airplane', word2: 'Helicopter', category: 'Tech & Transport', difficulty: 'easy' },
  { id: 't4', word1: 'Bicycle', word2: 'Skateboard', category: 'Tech & Transport', difficulty: 'easy' },
  { id: 't5', word1: 'Laptop', word2: 'Tablet', category: 'Tech & Transport', difficulty: 'medium' },
  { id: 't6', word1: 'Headphones', word2: 'Earbuds', category: 'Tech & Transport', difficulty: 'medium' },
  { id: 't7', word1: 'Camera', word2: 'Phone', category: 'Tech & Transport', difficulty: 'easy' },
  { id: 't8', word1: 'Ship', word2: 'Submarine', category: 'Tech & Transport', difficulty: 'easy' },
  { id: 't9', word1: 'Keyboard', word2: 'Piano', category: 'Tech & Transport', difficulty: 'medium' },
  { id: 't10', word1: 'Television', word2: 'Cinema', category: 'Tech & Transport', difficulty: 'medium' },
  { id: 't11', word1: 'Tram', word2: 'Monorail', category: 'Tech & Transport', difficulty: 'hard' },
  { id: 't12', word1: 'Drone', word2: 'Kite', category: 'Tech & Transport', difficulty: 'medium' },
  { id: 't13', word1: 'Rocket', word2: 'Missile', category: 'Tech & Transport', difficulty: 'hard' },
  { id: 't14', word1: 'Smartwatch', word2: 'Fitness Tracker', category: 'Tech & Transport', difficulty: 'hard' },
  { id: 't15', word1: 'Monitor', word2: 'Projector', category: 'Tech & Transport', difficulty: 'medium' },

  // Sports & Entertainment
  { id: 's1', word1: 'Soccer', word2: 'Basketball', category: 'Sports & Hobbies', difficulty: 'easy' },
  { id: 's2', word1: 'Tennis', word2: 'Badminton', category: 'Sports & Hobbies', difficulty: 'medium' },
  { id: 's3', word1: 'Chess', word2: 'Checkers', category: 'Sports & Hobbies', difficulty: 'medium' },
  { id: 's4', word1: 'Guitar', word2: 'Violin', category: 'Sports & Hobbies', difficulty: 'medium' },
  { id: 's5', word1: 'Flute', word2: 'Clarinet', category: 'Sports & Hobbies', difficulty: 'hard' },
  { id: 's6', word1: 'Drum', word2: 'Tambourine', category: 'Sports & Hobbies', difficulty: 'easy' },
  { id: 's7', word1: 'Novel', word2: 'Comic Book', category: 'Sports & Hobbies', difficulty: 'easy' },
  { id: 's8', word1: 'Painting', word2: 'Sculpture', category: 'Sports & Hobbies', difficulty: 'medium' },
  { id: 's9', word1: 'Bowling', word2: 'Billiards', category: 'Sports & Hobbies', difficulty: 'medium' },
  { id: 's10', word1: 'Skiing', word2: 'Snowboarding', category: 'Sports & Hobbies', difficulty: 'hard' },
  { id: 's11', word1: 'Baseball', word2: 'Cricket', category: 'Sports & Hobbies', difficulty: 'hard' },
  { id: 's12', word1: 'Ballet', word2: 'Hip Hop Dance', category: 'Sports & Hobbies', difficulty: 'easy' },
  { id: 's13', word1: 'Poem', word2: 'Song Lyrics', category: 'Sports & Hobbies', difficulty: 'hard' },
  { id: 's14', word1: 'Play', word2: 'Movie', category: 'Sports & Hobbies', difficulty: 'medium' },
  { id: 's15', word1: 'Microphone', word2: 'Megaphone', category: 'Sports & Hobbies', difficulty: 'medium' },

  // Roles, Professions & Characters
  { id: 'c1', word1: 'Doctor', word2: 'Nurse', category: 'Professions & Roles', difficulty: 'medium' },
  { id: 'c2', word1: 'Detective', word2: 'Police Officer', category: 'Professions & Roles', difficulty: 'medium' },
  { id: 'c3', word1: 'Chef', word2: 'Baker', category: 'Professions & Roles', difficulty: 'medium' },
  { id: 'c4', word1: 'Wizard', word2: 'Witch', category: 'Professions & Roles', difficulty: 'hard' },
  { id: 'c5', word1: 'Vampire', word2: 'Zombie', category: 'Professions & Roles', difficulty: 'easy' },
  { id: 'c6', word1: 'Pirate', word2: 'Sailor', category: 'Professions & Roles', difficulty: 'medium' },
  { id: 'c7', word1: 'Astronaut', word2: 'Alien', category: 'Professions & Roles', difficulty: 'easy' },
  { id: 'c8', word1: 'Actor', word2: 'Director', category: 'Professions & Roles', difficulty: 'medium' },
  { id: 'c9', word1: 'Teacher', word2: 'Professor', category: 'Professions & Roles', difficulty: 'hard' },
  { id: 'c10', word1: 'Judge', word2: 'Lawyer', category: 'Professions & Roles', difficulty: 'medium' },
  { id: 'c11', word1: 'King', word2: 'Prince', category: 'Professions & Roles', difficulty: 'medium' },
  { id: 'c12', word1: 'Ninja', word2: 'Samurai', category: 'Professions & Roles', difficulty: 'hard' },
  { id: 'c13', word1: 'Ghost', word2: 'Monster', category: 'Professions & Roles', difficulty: 'easy' },
  { id: 'c14', word1: 'Pilot', word2: 'Flight Attendant', category: 'Professions & Roles', difficulty: 'easy' },
  { id: 'c15', word1: 'Farmer', word2: 'Gardener', category: 'Professions & Roles', difficulty: 'medium' },

  // Abstract, Nuanced & Hard Concepts (High Social Deduction Stakes)
  { id: 'h1', word1: 'Whisper', word2: 'Murmur', category: 'Nuanced & Hard', difficulty: 'hard' },
  { id: 'h2', word1: 'Astronomy', word2: 'Astrology', category: 'Nuanced & Hard', difficulty: 'hard' },
  { id: 'h3', word1: 'Illusion', word2: 'Delusion', category: 'Nuanced & Hard', difficulty: 'hard' },
  { id: 'h4', word1: 'Poison', word2: 'Venom', category: 'Nuanced & Hard', difficulty: 'hard' },
  { id: 'h5', word1: 'Virus', word2: 'Bacteria', category: 'Nuanced & Hard', difficulty: 'hard' },
  { id: 'h6', word1: 'Biography', word2: 'Autobiography', category: 'Nuanced & Hard', difficulty: 'hard' },
  { id: 'h7', word1: 'Jealousy', word2: 'Envy', category: 'Nuanced & Hard', difficulty: 'hard' },
  { id: 'h8', word1: 'Courage', word2: 'Bravery', category: 'Nuanced & Hard', difficulty: 'hard' },
  { id: 'h9', word1: 'Rumor', word2: 'Gossip', category: 'Nuanced & Hard', difficulty: 'hard' },
  { id: 'h10', word1: 'Replica', word2: 'Counterfeit', category: 'Nuanced & Hard', difficulty: 'hard' },
  { id: 'h11', word1: 'Secret', word2: 'Mystery', category: 'Nuanced & Hard', difficulty: 'medium' },
  { id: 'h12', word1: 'Dream', word2: 'Nightmare', category: 'Nuanced & Hard', difficulty: 'easy' },
  { id: 'h13', word1: 'Memory', word2: 'Nostalgia', category: 'Nuanced & Hard', difficulty: 'hard' },
  { id: 'h14', word1: 'Labyrinth', word2: 'Maze', category: 'Nuanced & Hard', difficulty: 'hard' },
  { id: 'h15', word1: 'Sympathy', word2: 'Empathy', category: 'Nuanced & Hard', difficulty: 'hard' }
];
