export const GAME_CONSTANTS = {
  MIN_PLAYERS: 3,
  MAX_PLAYERS_DEFAULT: 10,
  DISCUSSION_DURATION_SECONDS: 60,
  WORD_REVEAL_TIMEOUT_SECONDS: 45,
  VOTING_DURATION_SECONDS: 45,
  MAX_ROUNDS: 5,
  SESSION_TOKEN_KEY: 'duodeceit_session',
  ROOM_CODE_LENGTH: 6,
} as const;
